id: I2AD0ED3D
legacy_id: P005626
ocr_import_info:
  bdrc_scan_id: W1KG3515
  source: bdrc
  ocr_info:
    timestamp: '2020-04-01T00:45:11'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T15:08:19.507252+00:00'
last_modified: 2022-08-31 23:08:58.864824
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG3515
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG3515
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཚད་མ་རྣམ་འགྲེལ་གྱི་འགྲེལ་པ་ལེགས་བཤད་སྣང་བའི་གཏེར།
  author: ཆོས་གྲགས།
statistics:
  ocr_word_mean_confidence_index: 0.9044565110318795
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG3599:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3599
      total_pages: 760
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3599.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9060323978510691
    legacy_id: v001
  I1KG3600:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3600
      total_pages: 1028
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG3600.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9032954624030378
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
