id: I2AD0ED3D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T00:52:01+00:00'
last_modified: '2022-06-08T05:23:40.324326+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3515
  title: ཚད་མ་རྣམ་འགྲེལ་གྱི་འགྲེལ་པ་ལེགས་བཤད་སྣང་བའི་གཏེར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8228':
      image_group_id: I1KG3599
      title: ''
      total_pages: 760
      order: 1
      base_file: 8228.txt
    89D2:
      image_group_id: I1KG3600
      title: ''
      total_pages: 1028
      order: 2
      base_file: 89D2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
